export default {
  "en": {
    "home": "Home",
    "page": "Page",
    "about": "About",
    "setting": "Setting",
    "logout": "Logout",
    "product": "Products",
    "solution": "Solutions",
    "document": "Document",
    "company": "Company",
    "price": "Pricing",
    "signin": "Sign In",
    "signup": "Sign Up",
    "pleaselogin": "Please Login",
    "email": "E-Mail Address",
    "remember": "Remember me",
    "login": "Login",
    "forgetpassword": "Forgot Your Password?",
    "signout": "Logout",
    "newregister": "Register New User",
    "register": "Register",
    "fullname": "Full Name",
    "firstname": "First name",
    "lastname": "Last name",
    "username": "Username",
    "password": "Password",
    "confirmpassword": "Confirm Password",
    "placeholderemail": "youname@iotlink.com.vn",
    "placeholderusername": "yourname",
    "usernameempty": "Username is empty",
    "emailempty": "Email is empty",
    "firstnameempty": "First name is empty",
    "lastnameempty": "Last name is empty",
    "passwordempty": "Password is empty",
    "confirmpasswordempty": "Confirm password is empty",
    "confirmpasswordincorect": "Confirm password is incorrect",
    "key": "Key"
  },
  "vi": {
    "home": "Trang chủ",
    "page": "Trang con",
    "about": "Về chúng tôi",
    "setting": "Cài đặt",
    "logout": "Thoát",
    "product": "Sản phẩm",
    "solution": "Giải pháp",
    "document": "Tài liệu",
    "company": "Về công ty",
    "price": "Giá",
    "signin": "Đăng nhập",
    "signup": "Đăng ký",
    "pleaselogin": "Vui lòng đăng nhập",
    "email": "Đăng nhập email",
    "remember": "Ghi nhớ đăng nhập",
    "login": "Đăng nhập",
    "forgetpassword": "Quên mật khẩu?",
    "signout": "Đăng xuất",
    "newregister": "Đăng ký người dùng mới",
    "register": "Đăng ký",
    "fullname": "Họ và tên",
    "firstname": "Họ và chữ lót",
    "lastname": "Tên",
    "username": "Tên đăng nhập",
    "password": "Mật khẩu",
    "confirmpassword": "Xác nhận lại mật khẩu",
    "placeholderemail": "nghiant@iotlink.com.vn",
    "placeholderusername": "nghiant",
    "usernameempty": "Tên đăng nhập bị trống",
    "emailempty": "Email bị trống",
    "firstnameempty": "Họ và chữ lót bị trống",
    "lastnameempty": "Tên bị trống",
    "passwordempty": "Mật khẩu bị trống",
    "confirmpasswordempty": "Mật khẩu xác nhận bị trống",
    "confirmpasswordincorect": "Mật khẩu xác nhận và mật khẩu không khớp",
    "key": "Key"
  }
}